In [1]:
import numpy as np

# Creating Arrays

In [2]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [4]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [6]:
n = np.array([[7,8,9], [10,11,12]])
n

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
n.shape

(2, 3)

In [10]:
n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [15]:
o = np.linspace(0,4,9) # similar to arange, we tell numpy how many values we want returned
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [17]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

## Numpy also several built-in shortcuts and functions for creating arrays

In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [23]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [28]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [30]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [31]:
x + y

array([5, 7, 9])

In [32]:
x * y

array([ 4, 10, 18])

In [33]:
x**2

array([1, 4, 9], dtype=int32)

In [39]:
x.dot(y)

32

In [43]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [44]:
z.shape

(2, 3)

In [45]:
z.T.shape

(3, 2)

In [46]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [47]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [48]:
z.dtype

dtype('int32')

In [50]:
z = z.astype('f')
z.dtype

dtype('float32')

In [51]:
a = np.array([-4,-2,1,3,5])

In [52]:
a.sum()

3

In [53]:
a.max()

5

In [54]:
a.min()

-4

In [55]:
a.mean()

0.6

In [56]:
a.std()

3.2619012860600183

In [57]:
a.argmax()

4

In [58]:
a.argmin()

0

## Indexing/Slicing

In [60]:
a = np.arange(13)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [61]:
a[0], a[4], a[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [62]:
a[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [63]:
a[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [64]:
a[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [67]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [68]:
r[2,2]

14

In [69]:
r[3,3:6]

array([21, 22, 23])

In [70]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [71]:
r[-1, ::2]

array([30, 32, 34])

In [73]:
r[r>30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [74]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [75]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [76]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## changing r2 led to a change in r
## if we want to create a copy that will not lead to a change in r, we'll use:

In [77]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [78]:
r_copy[:] = 10
print(r_copy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over Arrays

In [79]:
test = np.random.randint(0,10,(4,3))
test

array([[2, 2, 8],
       [2, 4, 2],
       [1, 6, 0],
       [8, 0, 3]])

In [80]:
for row in test:
    print(row)

[2 2 8]
[2 4 2]
[1 6 0]
[8 0 3]


In [81]:
for i in range(len(test)):
    print(test[i])

[2 2 8]
[2 4 2]
[1 6 0]
[8 0 3]


In [82]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [2 2 8]
row 1 is [2 4 2]
row 2 is [1 6 0]
row 3 is [8 0 3]


In [83]:
test2 = test**2
test2

array([[ 4,  4, 64],
       [ 4, 16,  4],
       [ 1, 36,  0],
       [64,  0,  9]], dtype=int32)

In [86]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i+j)

[2 2 8] + [ 4  4 64] = [ 6  6 72]
[2 4 2] + [ 4 16  4] = [ 6 20  6]
[1 6 0] + [ 1 36  0] = [ 2 42  0]
[8 0 3] + [64  0  9] = [72  0 12]


In [88]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [92]:
test[0:2,]

array([[2, 2, 8],
       [2, 4, 2]])

In [90]:
test

array([[2, 2, 8],
       [2, 4, 2],
       [1, 6, 0],
       [8, 0, 3]])

In [93]:
type(lambda x:x+1)

function